// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SmartTrip.Infrastructure.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260604113000_AddHotelGuestCounts")]
partial class AddHotelGuestCounts
{
}
