// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SmartTrip.Infrastructure.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260605000000_AddHotelCommissionRate")]
partial class AddHotelCommissionRate
{
}
